pipeline {
        environment {
        registry= "akashtawade/sparkdemo1"
        registryCredential= 'akash1493'
    }
    agent any
    stages {
        stage('Checkout') {
        steps {
            checkout([$class: 'GitSCM', branches: [[name: '*/master']], doGenerateSubmoduleConfigurations: false, extensions: [], submoduleCfg: [], userRemoteConfigs: [[credentialsId: '60b98677-dc9a-4783-bc69-21bb7a11d3ff', url: 'https://github.com/Lavanya-Prabhakar/Spark_Assignment_Practice.git']]])
            }
        }
        stage('Build') {
                 agent {
                    docker {
                      image 'maven:3-alpine'
                      args '-v /root/.m2:/root/.m2'
                }
            }
            
               steps {
                   dir ('C:\\Users\\Akash Tawade\\Desktop\\build.sh') { 
                    sh('./build.sh')
                    }
            }
            }
         stage('Test') {
            steps {
                echo 'Job has been test'
            }
        }
        stage('QA Deploy') {
            steps {
                echo 'Job has been deployed'
            }
        }
         stage('Prod Deploy') {
            steps {
                echo 'Production Deployment done'
            }
        }
    }
}

